#version: '3.8'
services:
  web:
    build: .
    ports:
      - "8060:8060"
    volumes:
      - .:/app
      - ../datasaki_data/arctic_lmdb:/data/arctic_lmdb
      - ../datasaki_data/models :/data/models
    depends_on:
      - db
#      - prometheus
#      - grafana

  engine:
    build: ../datasaki_engine/
    ports:
      - "50051:50051"
    volumes:
      - ../datasaki_engine:/app
      - ../datasaki_data/arctic_lmdb:/data/arctic_lmdb
      - ../datasaki_data/models :/data/models
    depends_on:
      - db
#      - prometheus
#      - grafana
#
#  ai:
#    build: ../datasaki_ai/
#    ports:
#      - "50061:50061"
#    volumes:
#      - ai_code:/app
#      - datasaki_arctic:/data/arctic_lmdb
#      - datasaki_models:/data/models
#    depends_on:
#      - db
#      - prometheus
#      - grafana

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9091"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"

#  traefik:
#    image: traefik:v2.5
#    ports:
#      - "80:80"
#      - "443:443"
#    command:
#      - "--api.insecure=true"
#      - "--providers.docker=true"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:

#volumes:
#  engine_code:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '../datasaki_engine'
#
#  datasaki_arctic:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '../datasaki_data/arctic_lmdb'
#
#  datasaki_db:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '../datasaki_data/postgres-data'
#
#  datasaki_models:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '../datasaki_data/models'