# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"i\n\tUserQuery\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x15\n\rsystem_prompt\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x15\n\x08industry\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_industry\" \n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t2B\n\x0b\x43hatService\x12\x33\n\x0c\x43hatWithGroq\x12\x0f.chat.UserQuery\x1a\x12.chat.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERQUERY']._serialized_start=20
  _globals['_USERQUERY']._serialized_end=125
  _globals['_CHATRESPONSE']._serialized_start=127
  _globals['_CHATRESPONSE']._serialized_end=159
  _globals['_CHATSERVICE']._serialized_start=161
  _globals['_CHATSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
